import Head from 'next/head'
import DashboardFAQs from '../../../components/DashboardFAQs'
import TopNavigation from '../../../components/TopNavigation'
import Footer from '../../../components/Footer/Footer'
import UserSelections from '../../../components/UserSelections'
import { useSession } from 'next-auth/react'
import {
  Box,
  Container,
} from '@mui/material'
import { hasToken } from '../../../utils/userAuth'


export async function getServerSideProps(context) {
  const token = await hasToken(context.req)
  if(!token) {
    return {
      redirect: {
        destination: '/invalid',
        permanent: false
      }
    }
  }
  return { props: {} }
}

const UserDashboard = () => {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Dashboard | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <Container sx={{ mt: 20, display: 'flex', justifyContent: 'space-between', flexDirection: 'column' }} maxWidth='xl'>
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <h2>Welcome, {session?.user.name}</h2>   
          <Box>
            <UserSelections />
          </Box>      
        </Box>
      </Container>
      <DashboardFAQs />
      <Footer />
    </>
  )
}

export default UserDashboard