// import { useState, useEffect } from 'react'
// import { hasToken } from '../../../utils/userAuth'
// import styles from '@/styles/my-profile.module.css'
import Head from 'next/head'
import PayDeposit from '../../../components/PayDeposit'
import Schedule from '../../../components/SelectSchedule'
import TopNavigation from '../../../components/TopNavigation'
import Footer from '../../../components/Footer/Footer'
import UserSelections from '../../../components/UserSelections'
import { useSession } from 'next-auth/react'
import {
  Box,
  Button,
  Container,
  Divider,
  List,
  ListItem,
  ListItemText,
} from '@mui/material'


// export async function getServerSideProps(context) {
//   const token = await hasToken(context.req)
//   if(!token) {
//     return {
//       redirect: {
//         destination: '/invalid',
//         permanent: false
//       }
//     }
//   }
//   return { props: {} }
// }

// export const getStaticPaths = async () => {
//   const res = await fetch('http://localhost:3000/api/routes/userData')
//   const data = await res.json()
//   console.log(data)

//   const paths = data.map(user => {
//     return {
//       params: { id: user.name.toString() }
//     }
//   })

//   return {
//     paths,
//     fallback: false
//   }
// }



// export const getStaticProps = async (context) => {
//   const id = context.params.id
//   const res = await fetch('/api/routes/userData/' + id)
//   const data = await res.json()

//   return {
//     props: { user: data }
//   }
// }

const userDashboard = () => {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>My Profile | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <Container sx={{ mt: 20, display: 'flex', justifyContent: 'space-between' }} maxWidth='xl'>
        <Box>
          <h2>Welcome, {session?.user.name}</h2>   
          <Box>
            <UserSelections />
          </Box>      
          <Box>
          {/* {userSelections.map((selection, index) => (
            <div key={index}>
                    ))}
                  </ListItem>
                </List>
              </Box>
            </div>
          */}
            <List component="nav" aria-label="mailbox folders">
              <ListItem>
                <ListItemText>
                  <h4>My current project: Spec Class Website</h4>
                </ListItemText>
              </ListItem>
              <ListItem >
                {/* <ListItemText primary={`Template Selection: ${selection.template}`} /> */}
                <ListItemText primary='Template Selection: Spitfire' />
              </ListItem>
              <Divider />
              <ListItem>
                {/* <ListItemText primary={`Color Choices: ${selection.colorChoices.map(element => ` ${element.colorChoice}`)}`} /> */}
                <ListItemText primary='Color Choices: Blue, Red, Yellow' />
              </ListItem>
              <ListItem>
                {/* <ListItemText primary={`Color choices bypassed? ${selection.colorBypass}`} /> */}
                <ListItemText primary='Color Choices bypassed? False' />
              </ListItem>
              <Divider />
              <ListItem >
                {/* <ListItemText primary={`Font Choices: ${selection.fontChoices.map(element => ` ${element.fontChoice}`)}`} /> */}
                <ListItemText primary='Font Choices: Oxygen, Bungee' />
              </ListItem>
              <ListItem>
                {/* <ListItemText primary={`Font choices bypassed? ${selection.fontBypass}`} /> */}
                <ListItemText primary='Font Choices bypassed? False' />
              </ListItem>
              <Divider />
              <ListItem >
                {/* <ListItemText primary={`Nav Links: ${selection.navLinks.map(element => ` ${element.navLink}`)}`} /> */}
                <ListItemText primary='Nav Links: Home, About, Gallery' />
              </ListItem>
              <Divider />
              <ListItem sx={{ flexDirection: 'column', alignItems: 'flex-start' }}>
                <ListItemText primary='Content' />
                {/* {selection.contentArea.map((element, index) => (
                  <ListItemText key={index} primary={`${element.contentItem}`} />
                ))} */}
              </ListItem>
              <Divider />

              </List>
            </Box>
        </Box>
        <Box style={{ display: 'flex' }} gap={4}>
          <Box style={{ display: 'flex', flexDirection: 'column' }} gap={2}>
            <Button variant='contained' style={{ backgroundColor: 'var(--mb1-4)', color: 'var(--char5)', fontSize: '20px', width: '200px', height: '100px' }} href='/get-started'>New Project</Button>
            <Button variant='contained' style={{ fontSize: '20px', width: '200px', height: '100px' }} disabled>Edit Project</Button>
          </Box>
          <Box style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', width: '400px' }} gap={2}>
            <h4>Balance Due</h4>
            <h4>$0.00</h4>
            <Button variant='contained' style={{ width: '200px' }} disabled>Pay Balance</Button>
            <PayDeposit />
            <Button variant='contained' style={{ backgroundColor: 'var(--mb1-1)', width: '200px' }}>View Invoice</Button>
            <p>Status: Not started</p>
            <p>Current completion date: 00/00/2023</p>
            <p style={{ color: 'greenyellow' }}>ON TRACK</p>
          </Box>
        </Box>
      </Container>
      <Schedule />
      <Footer />
    </>
  )
}

export default userDashboard