export const tabs = [
    { 
        name: "Single Page", 
        color: "var(--mb1-1)",
        title: "The single page website.",
        subtitle: "Feature rich, the one page site is surprisingly versatile.  Navigation, modals and pop-up galleries help the single webpage to feel technically complex and professional.",
        primaryText1: "Browse and select a starter template.",
        secondaryText1: "We have several options and more templates are being added all of the time.  Although this can be considered your jumping off point, many of the templates are fully functional and ready to go.",
        primaryText2: "Choose custom options.",
        secondaryText2: "This is where you start to make the templates your own.  Colors, fonts, navigation menu and overall layout are just a few of the things you can change.  You'll have the option to enter specific information at this point such as font names or hex codes for colors.  Alternatively, you can leave these fields blank and simply check a box indicating you'd like to discuss custom options during our initial 1x1.", 
        primaryText3: "Add content and enter additional details or instructions.",
        secondaryText3: "As with the previous step, here you will have the ability to enter specifics or leave them blank and simply check a box letting us know to discuss at a later point.  Keep in mind that the more information you can provide on day one, the more likely your estimated time to completion (or ETC) will be reduced.  Some examples of information you might provide at this point would be a paragraph for the About section of your site or the names of navigation links and content blocks within the site (i.e., News, About, Gallery, Contact, etc.).", 
        primaryText4: "Schedule your site's estimated completion date and 1x1's.",
        secondaryText4: "The estimated date your site will be ready to go live is based on several different factors and should be considered a moving target (to some extent).  Developer availability, level of customization or whether all content is available from day one can affect your date.  For single page websites you can also schedule up to three one-hour live Zoom sessions.  Typically we would connect before and during development and then a final time before launch.  While you can connect with your developer via email at any point during this process, we feel there is nothing like getting together over Zoom to make sure everyone is on the same page.", 
        primaryText5: "Finalize selections and submit deposit.",
        secondaryText5: "A summary will be generated at the end for you to review and ammend as needed.  The summarized information is not set in stone and most things can be changed up until the site is launched.  Please note that deposits are non-refundable after 24 hours from the point you click Submit.",
        href: "/get-started/singlepage" 
    },
    { 
        name: "Multi Page", 
        color: "var(--mb1-2)", 
        title: "More square footage.",
        subtitle: "When you simply need more space now or room to grow in the future, the multi page website is the clear choice.  Incorporate blogs, dedicated gallery or product pages and much more.",
        primaryText1: "Browse and select a starter template.",
        secondaryText1: "Multiple options available.  Although this can be considered your jumping off point, many of the templates are fully functional and ready to go.",
        primaryText2: "Choose custom options.",
        secondaryText2: "This is where you start to make the templates your own.  Colors, fonts, navigation menu and overall layout are just a few of the things you can change.  You'll have the option to enter specific information at this point such as font names or hex codes for colors.  Alternatively, you can leave these fields blank and simply check a box indicating you'd like to discuss custom options during our initial 1x1.", 
        primaryText3: "Enter additional page details such as their name and purpose.",
        secondaryText3: "Here you will also have the ability to enter specifics or leave them blank and simply check a box letting us know to discuss at a later point.  Keep in mind that the more information you can provide on day one, the more likely your estimated time to completion (or ETC) will be reduced.  Some examples of information you might provide at this point would be a paragraph for the About section of your site or the names of navigation links and additional pages within the site (i.e., News, About, Gallery, Contact, etc.).", 
        primaryText4: "Schedule your site's estimated completion date and 1x1's.",
        secondaryText4: "The estimated date your site will be ready to go live is based on several different factors and should be considered a moving target (to some extent).  Developer availability, level of customization or whether all content is available from day one can affect your date.  For multi page websites you can also schedule up to five one-hour live Zoom sessions.  Typically we would connect before and during development and then a final time before launch.  While you can connect with your developer via email at any point during this process, we feel there is nothing like getting together over Zoom to make sure everyone is on the same page.", 
        primaryText5: "Finalize selections and submit deposit.",
        secondaryText5: "A summary will be generated at the end for you to review and ammend as needed.  The summarized information is not set in stone and most things can be changed up until the site is launched.  Please note that deposits are non-refundable after 24 hours from the point you click Submit.",
        href: "/get-started/multipage" 
    },
    { 
        name: "Custom", 
        color: "var(--mb2-1)", 
        title: "When one size doesn't fit all.",
        subtitle: "We are happy to work with you on a site that goes above and beyond our standard offerings.  Click Get Started to complete the custom site quote form.",
        primaryText1: "Choose one of our templates as a baseline or provide an overview.",
        secondaryText1: "The first part of the form allows you to select one of our templates as a jumping off point for your custom site.  Alternatively, there is a section where you can write a high-level overview of what the website's primary function and layout will be.",
        primaryText2: "Provide any custom options.",
        secondaryText2: "Similar to the other products we offer, if you know the colors, fonts or anything else, feel free to enter that information at this stage.", 
        primaryText3: "Provide any content or further details.",
        secondaryText3: "Here you will also have the ability to enter specifics or leave them blank and simply check a box letting us know to discuss at a later point.  Keep in mind that the more information you can provide on day one, the more likely your estimated time to completion (or ETC) will be reduced.  Some examples of information you might provide at this point would be a paragraph for the About section of your site or the names of navigation links and additional pages within the site (i.e., News, About, Gallery, Contact, etc.).", 
        primaryText4: "Schedule your inital consultation.",
        secondaryText4: "Since we don't yet know the end goals, it can be difficult to provide an estimated time of completion (or ETC) at this stage.  You will have the ability to schedule the initial consultation, however.", 
        primaryText5: "Review summary.",
        secondaryText5: "Take a look at all of the information you've provided and confirm the scheduled 1x1.  No deposits required at this stage in the process.",
        href: "/get-started/contact" 
    },
];