export const tabs = [
    { 
        name: "Single Page", 
        color: "var(--mb1-1)",
        title: "The single page website.",
        subtitle: "Feature rich, the one page site is surprisingly versatile.  Navigation, modals and pop-up galleries help the single webpage to feel technically complex and professional.",
        primaryText1: "Primary Text",
        secondaryText1: "Secondary Text",
        primaryText2: "Primary Text",
        secondaryText2: "Secondary Text", 
        primaryText3: "Primary Text",
        secondaryText3: "Secondary Text", 
        primaryText4: "Primary Text",
        secondaryText4: "Secondary Text", 
        primaryText5: "Primary Text",
        secondaryText5: "Secondary Text",
        href: "/get-started/singlepage" 
    },
    { 
        name: "Multi Page", 
        color: "var(--mb1-2)", 
        title: "More square footage.",
        subtitle: "When you simply need more space now or room to grow in the future, the multi page website is the clear choice.  Incorporate blogs, dedicated gallery or product pages and much more.",
        primaryText1: "Primary Text",
        secondaryText1: "Secondary Text",
        primaryText2: "Primary Text",
        secondaryText2: "Secondary Text", 
        primaryText3: "Primary Text",
        secondaryText3: "Secondary Text", 
        primaryText4: "Primary Text",
        secondaryText4: "Secondary Text", 
        primaryText5: "Primary Text",
        secondaryText5: "Secondary Text",
        href: "/get-started/multipage" 
    },
    { 
        name: "Custom", 
        color: "var(--mb2-1)", 
        title: "When one size doesn't fit all.",
        subtitle: "We are happy to work with you on a site that goes above and beyond our standard offerings.  The best way to get started is by contacting us.",
        primaryText1: "Primary Text",
        secondaryText1: "Secondary Text",
        primaryText2: "Primary Text",
        secondaryText2: "Secondary Text", 
        primaryText3: "Primary Text",
        secondaryText3: "Secondary Text", 
        primaryText4: "Primary Text",
        secondaryText4: "Secondary Text", 
        primaryText5: "Primary Text",
        secondaryText5: "Secondary Text",
        href: "/get-started/contact" 
    },
];