import Head from 'next/head'
import clientPromise from '../../lib/mongodb'
import styles from '@/styles/basics.module.css'
import TopNavigation from '../../components/TopNavigation'
import BannerHeader from '../../components/BannerHeader'
import BasicsCards from '../../components/Basics'
import Footer from '../../components/Footer/Footer'

export async function getServerSideProps() {
  try {
    await clientPromise
    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}

export default function Basics({isConnected}) {
  return (
    <>
      <Head>
        <title>Single Page | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <BannerHeader 
        tag1='We offer two primary foundations.'
        tag2='Start with a single page or multi-page site.'
        subtag='Complex understanding'
        subtext1='Here you&apos;ll find an overview of how the process works.'
        subtext2='This is a jumping-off point.  Your site will be tailor-made for your application.'
      />
      <main className={styles.main}>
          <BasicsCards />
      </main>
      <Footer />
    </>
  )
}
