import Head from 'next/head'
import TopNavigation from '../../components/TopNavigation'
import BannerHeader from '../../components/BannerHeader'
import Footer from '../../components/Footer/Footer'
import FaQuestions from '../../components/Faq/index'
import {
  Card,
  CardContent,
  Container
} from '@mui/material'
import Contact from '../../components/Contact'


export default function FAQS() {
  return (
    <>
      <Head>
        <title>FAQ&apos;S | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <BannerHeader 
        tag1='Answers.'
        subtext1='Feel free to contact us if you need more information.'
      />
      <Container maxWidth sx={{ mt: 10, mb: 10 }}>
        <Card raised>
          <CardContent>
            <FaQuestions />
          </CardContent>
        </Card>
      </Container>
      <Contact />
      <Footer />
    </>
  )
}