import Head from 'next/head'
import Image from 'next/image'
import clientPromise from '../../lib/mongodb'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TopNavigation from '../../components/TopNavigation'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
  try {
    await clientPromise
    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}

export default function Home({isConnected}) {
  return (
    <>
      <Head>
        <title>Home | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavigation />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1>Turn17 Media</h1>
          <h2>Coming Soon</h2>
            {isConnected ? (
          <>
          ...db connected...
          </>
        ) : (
          <p className="subtitle">
            You are NOT connected to MongoDB. Check the <code>README.md</code>{' '}
            for instructions.
          </p>
        )}
        </div>
      </main>
    </>
  )
}
