import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import TopNavigation from '../../components/TopNavigation'
import BannerHeader from '../../components/BannerHeader'
import MainFeatures from '../../components/MainFeatures'
import DownArrow from '../../components/DownArrow'
import Parallax from '../../components/Parallax/Parallax'
import FinishedSiteEx from '../../components/FinishedSiteExample'
import Contact from '../../components/Contact'
import Footer from '../../components/Footer/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <BannerHeader 
        tag1='Design a website on your terms'
        tag2='with a clear pricing structure.'
        subtag='If you have to ask, you can&apos;t afford it'
        subtext1='Understand what you&apos;re getting and how much it will cost from day one.'
        subtext2='A secure, professional website doesn&apos;t need to be complicated.'
      />
      <main className={styles.main}>
        <div className={styles.center}>
          <MainFeatures />
          <DownArrow />
          <Parallax />
          <DownArrow />
          <FinishedSiteEx />
          <Contact />
        </div>
      </main>
      <Footer />
    </>
  )
}
