import Head from 'next/head'
import clientPromise from '../../lib/mongodb'
import styles from '@/styles/singlepage.module.css'
import TopNavigation from '../../components/TopNavigation'
import BannerHeader from '../../components/BannerHeader'
import Footer from '../../components/Footer/Footer'

export async function getServerSideProps() {
  try {
    await clientPromise
    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}

export default function Contact({isConnected}) {
  return (
    <>
      <Head>
        <title>Please Login | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <BannerHeader 
        tag1='Missed a gear?'
        // subtag='Hidden fees'
        subtext1='Sorry, you must be logged in to access that page.'
        subtext2='Please register or login to continue.'
      />
      <Footer />
    </>
  )
}
