import Head from 'next/head'
import clientPromise from '../../lib/mongodb'
import styles from '@/styles/Home.module.css'
import TopNavigation from '../../components/TopNavigation'
import Button from '../../components/Button/index'
import Footer from '../../components/Footer/Footer'
import { useSession } from 'next-auth/react'


export async function getServerSideProps() {
  try {
    const client = await clientPromise
    const db = client.db("turn17_media")
    const userSelections = await db
      .collection("selections")
      .find({
        "email" : "laurelbrick@gmail.com"
      })
      .sort({ "_id" : -1 })
      .limit(10)
      .toArray()
    return {
      props: { userSelections: JSON.parse(JSON.stringify(userSelections)) },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false }
    }
  }
}

const MyProfile = ({ userSelections }) => {
  const { data: session } = useSession()
  console.log(userSelections)

  return (
    <>
      <Head>
        <title>My Profile | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <main>
        <div style={{ minHeight: '60vh', marginTop: '102px', display: 'flex', flexDirection: 'column', alignItems: 'flex-end', padding: '20px' }}>
          <h2>Welcome, {session?.user.name}</h2>
          {userSelections.map((selection, index) => (
            <div key={index}>
            <p>Template selection: {selection.template}</p>
            <p>Email: {selection.email}</p>
            </div>
          ))}
          
          
        </div>
        <Footer />
      </main>
    </>
  )
}

export default MyProfile