import * as React from 'react'
import styles from '@/styles/my-profile.module.css'
import Head from 'next/head'
import clientPromise from '../../lib/mongodb'
import TopNavigation from '../../components/TopNavigation'
import Footer from '../../components/Footer/Footer'
import { useSession } from 'next-auth/react'
import {
  AppBar,
  Avatar,
  Box,
  Button,
  Collapse,
  Container,
  Divider,
  IconButton,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  ListSubheader,
  Menu,
  MenuItem,
  Toolbar
} from '@mui/material'


export async function getServerSideProps() {
  try {
    const client = await clientPromise
    const db = client.db("turn17_media")
    const userSelections = await db
      .collection("selections")
      .find({
        "email" : "laurelbrick@gmail.com"
      })
      .sort({ "_id" : -1 })
      .limit(10)
      .toArray()
    return {
      props: { userSelections: JSON.parse(JSON.stringify(userSelections)) },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false }
    }
  }
}

const MyProfile = ({ userSelections }) => {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>My Profile | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <Container sx={{ minHeight: '50vh', mt: 20 }} maxWidth='xl'>
          <h2>Welcome, {session?.user.name}</h2>
          {userSelections.map((selection, index) => (
            <div key={index}>
              <h4>My current project: Spec Class Website</h4>
              <Box sx={{ width: '40%' }}>
                <List component="nav" aria-label="mailbox folders">
                  <ListItem >
                    <ListItemText primary={`Template Selection: ${selection.template}`} />
                  </ListItem>
                  <Divider />
                  <ListItem>
                    <ListItemText primary={`Color Choices: ${selection.colorChoices.map(element => ` ${element.colorChoice}`)}`} />
                  </ListItem>
                  <ListItem>
                    <ListItemText primary={`Color choices bypassed? ${selection.colorBypass}`} />
                  </ListItem>
                  <Divider />
                  <ListItem >
                    <ListItemText primary={`Font Choices: ${selection.fontChoices.map(element => ` ${element.fontChoice}`)}`} />
                  </ListItem>
                  <ListItem>
                    <ListItemText primary={`Font choices bypassed? ${selection.fontBypass}`} />
                  </ListItem>
                  <Divider />
                  <ListItem >
                    <ListItemText primary={`Nav Links: ${selection.navLinks.map(element => ` ${element.navLink}`)}`} />
                  </ListItem>
                </List>
              </Box>
            </div>
          ))}
          
          
      </Container>
      <Footer />
    </>
  )
}

export default MyProfile