import { useState, useEffect } from 'react'
import styles from '@/styles/my-profile.module.css'
import Head from 'next/head'
import TopNavigation from '../../components/TopNavigation'
import Footer from '../../components/Footer/Footer'
import { useSession } from 'next-auth/react'
import {
  Box,
  Button,
  Collapse,
  Container,
  Divider,
  IconButton,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  ListSubheader,
  Menu,
  MenuItem,
  Toolbar
} from '@mui/material'


const MyProfile = () => {
  const { data: session } = useSession()
  const email = session?.user.email

  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)
 
  useEffect(() => {
    setLoading(true)
    fetch('/api/routes/profile-data', {
      method: 'GET',
      headers: {
        "Content-Type": "application/json"
      },
      body: email
    })
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
        console.log(data)
      })
  }, [])
 
  if (isLoading) return <p>Loading...</p>
  if (!data) return <p>No profile data</p>

  return (
    <>
      <Head>
        <title>My Profile | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <Container sx={{ minHeight: '50vh', mt: 20 }} maxWidth='xl'>
          <h2>Welcome, {session?.user.name}</h2>
          {/* <h4>Email: {data.userSelections[0].email}</h4> */}
          {/* {userSelections.map((selection, index) => (
            <div key={index}>
              <h4>My current project: Spec Class Website</h4>
              <Box sx={{ width: '40%' }}>
                <List component="nav" aria-label="mailbox folders">
                  <ListItem>
                    <ListItemText />
                  </ListItem>
                  <ListItem >
                    <ListItemText primary={`Template Selection: ${selection.template}`} />
                  </ListItem>
                  <Divider />
                  <ListItem>
                    <ListItemText primary={`Color Choices: ${selection.colorChoices.map(element => ` ${element.colorChoice}`)}`} />
                  </ListItem>
                  <ListItem>
                    <ListItemText primary={`Color choices bypassed? ${selection.colorBypass}`} />
                  </ListItem>
                  <Divider />
                  <ListItem >
                    <ListItemText primary={`Font Choices: ${selection.fontChoices.map(element => ` ${element.fontChoice}`)}`} />
                  </ListItem>
                  <ListItem>
                    <ListItemText primary={`Font choices bypassed? ${selection.fontBypass}`} />
                  </ListItem>
                  <Divider />
                  <ListItem >
                    <ListItemText primary={`Nav Links: ${selection.navLinks.map(element => ` ${element.navLink}`)}`} />
                  </ListItem>
                  <Divider />
                  <ListItem sx={{ flexDirection: 'column', alignItems: 'flex-start' }}>
                    <ListItemText primary='Content' />
                    {selection.contentArea.map((element, index) => (
                      <ListItemText key={index} primary={`${element.contentItem}`} />
                    ))}
                  
                    

                  </ListItem>
                </List>
              </Box>
            </div>
          ))} */}
          
          
      </Container>
      <Footer />
    </>
  )
}

export default MyProfile