import Head from 'next/head'
import Image from 'next/image'
import clientPromise from '../../lib/mongodb'
import styles from '@/styles/Pricing.module.css'
import TopNavigation from '../../components/TopNavigation'
import BannerHeader from '../../components/BannerHeader'
import Footer from '../../components/Footer/Footer'


export async function getServerSideProps() {
  try {
    await clientPromise
    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}

export default function Pricing({isConnected}) {
  return (
    <>
      <Head>
        <title>Pricing | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <BannerHeader 
        tag1='What will this actually cost?'
        subtag='Hidden fees'
        subtext1='As champions of transparency, Turn17 Media will always be upfront with pricing.'
        subtext2='Shopping for a website shouldn&apos;t take place in the dark.  Know the final figure before you pull the trigger.'
      />

      <main className={styles.main}>

      </main>
      <Footer />
    </>
  )
}
