import Head from 'next/head'
import styles from '@/styles/Pricing.module.css'
import TopNavigation from '../../components/TopNavigation'
import BannerHeader from '../../components/BannerHeader'
import Footer from '../../components/Footer/Footer'
import PricingCards from '../../components/PricingCards/pricing'
import Contact from '../../components/Contact'



export default function Pricing() {
  return (
    <>
      <Head>
        <title>Pricing | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <BannerHeader 
        tag1='What will this actually cost?'
        subtag='Hidden fees'
        // subtext1='As champions of transparency, Turn17 Media will always be upfront with pricing.'
        subtext2='Shopping for a website shouldn&apos;t take place in the dark.  Know the final figure before you pull the trigger.'
      />
      <PricingCards />
      <main className={styles.main}>
        <Contact />
      </main>
      <Footer />
    </>
  )
}
