import Head from 'next/head'
import TopNavigation from '../../components/TopNavigation'
import WebDesignMain from '../../components/WebDesign'
import Footer from '../../components/Footer/Footer'
import Contact from '../../components/Contact'
import CalendlyScheduler from '../../components/CalendlyScheduler/CalendlyScheduler'



export default function WebDesign() {
  return (
    <>
      <Head>
        <title>Web Design | Turn17 Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/turn17-media-tab-logo.jpg" />
      </Head>
      <TopNavigation />
      <WebDesignMain />
      <Contact />
      <CalendlyScheduler />
      <Footer />
    </>
  )
}
